// Cards
export const CARDS_LEGEND = [
  'legend/SoccerCrypto-player-Pogba.png',
  'legend/SoccerCrypto-player-messi.png',
  'legend/SoccerCrypto-player-neymar.png',
  'legend/SoccerCrypto-player-ronaldo.png',
]
export const CARDS_COMMON = [
  'common/SoccerCrypto-player-1.png',
  'common/SoccerCrypto-player-2.png',
  'common/SoccerCrypto-player-Ahmed Zain.png',
  'common/SoccerCrypto-player-Alejandro Brand.png',
  'common/SoccerCrypto-player-Alphonso Davies.png',
  'common/SoccerCrypto-player-Chicharito.png',
  'common/SoccerCrypto-player-Hannibal Mejbri.png',
  'common/SoccerCrypto-player-Harry Wilson.png',
  'common/SoccerCrypto-player-Layer 39.png',
  'common/SoccerCrypto-player-Luka Jovic.png',
  'common/SoccerCrypto-player-Thomas Partey.png',
  'common/SoccerCrypto-player-bdessamad Ezzalzouli.png',
  'common/SoccerCrypto-player-carcelen.png',
  'common/SoccerCrypto-player-eisa ahmed palangi.png',
]
export const CARDS_RARE = [
  'rare/Shahab Zahedi.png',
  'rare/SoccerCrypto-player-Christian Pulisic.png',
  'rare/SoccerCrypto-player-Mbabu.png',
  'rare/SoccerCrypto-player-cavani.png',
  'rare/SoccerCrypto-player-lewandowski.png',
  'rare/SoccerCrypto-player-minamino.png',
  'rare/SoccerCrypto-player-sadio mane.png',
  'rare/SoccerCrypto-player-son heung min.png',
]
export const CARDS_EPIC = [
  'epic/SoccerCrypto-player-Frenkie de Jong.png',
  'epic/SoccerCrypto-player-Lukaku.png',
  'epic/SoccerCrypto-player-Toni kroos.png',
  'epic/SoccerCrypto-player-harry kane.png',
  'epic/SoccerCrypto-player-luka modric.png',
  'epic/SoccerCrypto-player-sergio ramos.png',
]

// Equips
export const EQUIPS_COMMON = [
  'equipments/common/baker hat.png',
  'equipments/common/chartreuse.png',
  'equipments/common/chelse shoes.png',
  'equipments/common/chemistry gloves.png',
  'equipments/common/cover glasses.png',
  'equipments/common/espa shoes.png',
  'equipments/common/frog glasses.png',
  'equipments/common/green hat.png',
  'equipments/common/green shoes.png',
  'equipments/common/green soldier.png',
  'equipments/common/green tail.png',
  'equipments/common/kai gloves.png',
  'equipments/common/labor gloves.png',
  'equipments/common/mon shoes.png',
  'equipments/common/packing gloves.png',
  'equipments/common/pilot hat.png',
  'equipments/common/plastic gloves.png',
  'equipments/common/sheriff hat.png',
  'equipments/common/simple glass.png',
  'equipments/common/simple gloves.png',
  'equipments/common/sliper.png',
  'equipments/common/sneaker shoes.png',
  'equipments/common/thin glasses.png',
  'equipments/common/tuxedo hat.png',
]

export const EQUIPS_RARE = [
  'equipments/rare/aLien hat.png',
  'equipments/rare/blue glasses.png',
  'equipments/rare/blue gloves.png',
  'equipments/rare/blue tail.png',
  'equipments/rare/boad shoes.png',
  'equipments/rare/brogue shoes.png',
  'equipments/rare/captain hat.png',
  'equipments/rare/chuk shoes.png',
  'equipments/rare/cinema glasses.png',
  'equipments/rare/cover gloves.png',
  'equipments/rare/cyan glasses.png',
  'equipments/rare/fedora hat.png',
  'equipments/rare/ford shoes.png',
  'equipments/rare/goalie gloves.png',
  'equipments/rare/hobnailed.png',
  'equipments/rare/insu gloves.png',
  'equipments/rare/kan gloves.png',
  'equipments/rare/kun gloves.png',
  'equipments/rare/Layer 30.png',
  'equipments/rare/monk shoes.png',
  'equipments/rare/spy glasses.png',
  'equipments/rare/technology.png',
  'equipments/rare/worker hat.png',
  'equipments/rare/xmen glasses.png',
]

export const EQUIPS_EPIC = [
  'equipments/epic/derby shoes.png',
  'equipments/epic/fire gloves.png',
  'equipments/epic/Layer 33.png',
  'equipments/epic/Layer 37.png',
  'equipments/epic/Layer 40.png',
  'equipments/epic/Layer 43.png',
  'equipments/epic/Layer 45.png',
  'equipments/epic/Layer 46.png',
  'equipments/epic/Layer 47 copy 14.png',
  'equipments/epic/Layer 47 copy 15.png',
  'equipments/epic/Layer 72.png',
  'equipments/epic/Layer 79.png',
  'equipments/epic/Layer 80.png',
  'equipments/epic/Layer 82.png',
  'equipments/epic/Layer 83.png',
  'equipments/epic/Layer 84 copy.png',
  'equipments/epic/sport shoes.png',
  'equipments/epic/vapor shoes.png',
  'equipments/epic/vas shoes.png',
  'equipments/epic/violet gloves.png',
]

export const EQUIPS_LEGEND = [
  'equipments/legend/af shoes.png',
  'equipments/legend/dragonfly glasses.png',
  'equipments/legend/explore glasses.png',
  'equipments/legend/explore hat.png',
  'equipments/legend/gold gloves.png',
  'equipments/legend/moto hat.png',
  'equipments/legend/movie glasses.png',
  'equipments/legend/nike air shoes.png',
  'equipments/legend/nike shoes.png',
  'equipments/legend/red gloves.png',
  'equipments/legend/RED HAT.png',
  'equipments/legend/ruby gloves.png',
  'equipments/legend/super hat.png',
  'equipments/legend/super shoes.png',
  'equipments/legend/thanos gloves.png',
  'equipments/legend/vr glasses.png',
]
